-- 新数据库初始化脚本，可重复执行；旧数据库只执行 SQL/migrations 中未应用的迁移。


CREATE TABLE IF NOT EXISTS user (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 userAccount VARCHAR(256) NOT NULL,
 userPassword VARCHAR(512) NOT NULL,
 userName VARCHAR(256), userAvatar VARCHAR(1024), userProfile VARCHAR(512),
 userRole VARCHAR(256) NOT NULL DEFAULT 'user',
 vipExpireTime DATETIME, vipCode VARCHAR(128), vipNumber BIGINT,
 shareCode VARCHAR(20), inviteUser BIGINT,
 editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 isDelete TINYINT NOT NULL DEFAULT 0,
 UNIQUE KEY uk_userAccount (userAccount), INDEX idx_userName (userName)
);
CREATE TABLE IF NOT EXISTS picture (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 url VARCHAR(512) NOT NULL, thumbnailUrl VARCHAR(512), originalKey VARCHAR(512),
 name VARCHAR(128) NOT NULL, introduction VARCHAR(512), category VARCHAR(64), tags VARCHAR(512),
 picSize BIGINT, picWidth INT, picHeight INT, picScale DOUBLE, picFormat VARCHAR(32), picColor VARCHAR(16),
 userId BIGINT NOT NULL, spaceId BIGINT,
 reviewStatus INT NOT NULL DEFAULT 0, reviewMessage VARCHAR(512), reviewerId BIGINT, reviewTime DATETIME,
 createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 isDelete TINYINT NOT NULL DEFAULT 0,
 INDEX idx_space_review_time (spaceId, isDelete, reviewStatus, createTime),
 INDEX idx_userId (userId), INDEX idx_category (category)
);
CREATE TABLE IF NOT EXISTS space (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, spaceName VARCHAR(128), spaceLevel INT NOT NULL DEFAULT 0,
 maxSize BIGINT NOT NULL DEFAULT 0, maxCount BIGINT NOT NULL DEFAULT 0,
 totalSize BIGINT NOT NULL DEFAULT 0, totalCount BIGINT NOT NULL DEFAULT 0,
 userId BIGINT NOT NULL,
 createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 isDelete TINYINT NOT NULL DEFAULT 0,
 INDEX idx_space_userId (userId), INDEX idx_spaceName (spaceName)
);
